//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Data/Inputs/Player/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""ThirdPersonCharacter_ActionMap"",
            ""id"": ""76bb3a25-3690-4166-9e14-efcc3592a1db"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""13446cbb-5fce-4f61-ac96-7e5ce6033f62"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6853d0a2-12f2-4ba1-b78d-a9f829952170"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Value"",
                    ""id"": ""a2900d22-7b28-4e57-898b-a7fd4ecf8255"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""2541a17b-819c-42a0-a3b2-94e6aee7deda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Value"",
                    ""id"": ""768668a1-67ef-4012-8182-599fcbb2c13c"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""d951d56c-3739-4029-9a76-b59e51c21731"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectWeapon0"",
                    ""type"": ""Button"",
                    ""id"": ""8b755986-5c9b-4b19-8c9c-2b57ee62e3d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeapon1"",
                    ""type"": ""Button"",
                    ""id"": ""b58489f7-0446-4d91-ae50-8c2282478d31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeapon2"",
                    ""type"": ""Button"",
                    ""id"": ""68cf6ad2-4f6d-4c35-aab9-7c0021c8085e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeapon3"",
                    ""type"": ""Button"",
                    ""id"": ""7a3547de-525a-4b32-88e0-a68b9db38d1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeapon4"",
                    ""type"": ""Button"",
                    ""id"": ""61a25f04-a752-40cf-8014-5a94dc485930"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeapon5"",
                    ""type"": ""Button"",
                    ""id"": ""05465fe1-1bcf-4018-8937-743b16e3c519"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeapon6"",
                    ""type"": ""Button"",
                    ""id"": ""c1450a2d-31fd-4d92-8ecd-9d7435318e85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeapon7"",
                    ""type"": ""Button"",
                    ""id"": ""ded9df40-8d07-46be-afc5-a0d2578fd3b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeapon8"",
                    ""type"": ""Button"",
                    ""id"": ""153447d3-60c4-4db1-a01f-36be03ffb666"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeapon9"",
                    ""type"": ""Button"",
                    ""id"": ""b61af5c4-ad75-42c7-9e74-bd1c5cbbf003"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Locking"",
                    ""type"": ""Value"",
                    ""id"": ""25776f52-0aa3-41da-88d8-9c5edf0d36a0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f454e865-8998-460f-bb41-f2afb643de8d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2235cdbf-aacd-4f72-bc17-88bd8ce85f47"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d2f54637-e3e6-4461-80d0-91f68a70f0af"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""65d3c1d7-c6c1-400a-858b-ee853a938ee9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2126875e-7044-4efe-89a0-491dcef3fd86"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""66a97e8c-58fc-4943-b796-025163f4140c"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01645eb4-4100-4a08-a4dc-b8be493f2c2e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eea5429-f0d8-49b2-b91b-0249c381548f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c6a9daf-291c-45c3-8692-690d396bf8b7"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e500e86c-a890-4a27-b5f4-5b055c2d6824"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15cb0e88-0e93-4254-83cb-8597e14afed1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0565866-ce51-453c-b875-47801eccde0f"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77310f4d-ae32-42bf-8e96-f305c91d0046"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbdc2c8f-9ecf-49be-9eb2-8e37644fb83c"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2521935-ed2f-4b2a-b98d-7a59f835c824"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da0536d1-f786-4689-8475-eb59420f2b2e"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a14ffb54-9713-4ae9-a1a6-4d42a1c39e18"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9baadf4-1085-4679-8b5a-9ff23c5c109d"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea153766-cb35-42a6-b736-b5f928303e45"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c299e6c3-7612-43b7-9f58-a27fdfffad63"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db56d3ab-2ab1-4380-920c-c9ce493029bf"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""766ff480-9d99-4c57-9e1d-e93ef56a7290"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeapon9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""871be624-a7fe-4f19-9199-fa7c0f4f6ec8"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Locking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ThirdPersonCharacter_ActionMap
        m_ThirdPersonCharacter_ActionMap = asset.FindActionMap("ThirdPersonCharacter_ActionMap", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_Move = m_ThirdPersonCharacter_ActionMap.FindAction("Move", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_Jump = m_ThirdPersonCharacter_ActionMap.FindAction("Jump", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_Run = m_ThirdPersonCharacter_ActionMap.FindAction("Run", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_Crouch = m_ThirdPersonCharacter_ActionMap.FindAction("Crouch", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_Shoot = m_ThirdPersonCharacter_ActionMap.FindAction("Shoot", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_ChangeWeapon = m_ThirdPersonCharacter_ActionMap.FindAction("ChangeWeapon", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon0 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon0", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon1 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon1", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon2 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon2", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon3 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon3", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon4 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon4", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon5 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon5", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon6 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon6", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon7 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon7", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon8 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon8", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_SelectWeapon9 = m_ThirdPersonCharacter_ActionMap.FindAction("SelectWeapon9", throwIfNotFound: true);
        m_ThirdPersonCharacter_ActionMap_Locking = m_ThirdPersonCharacter_ActionMap.FindAction("Locking", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ThirdPersonCharacter_ActionMap
    private readonly InputActionMap m_ThirdPersonCharacter_ActionMap;
    private List<IThirdPersonCharacter_ActionMapActions> m_ThirdPersonCharacter_ActionMapActionsCallbackInterfaces = new List<IThirdPersonCharacter_ActionMapActions>();
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_Move;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_Jump;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_Run;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_Crouch;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_Shoot;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_ChangeWeapon;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon0;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon1;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon2;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon3;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon4;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon5;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon6;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon7;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon8;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_SelectWeapon9;
    private readonly InputAction m_ThirdPersonCharacter_ActionMap_Locking;
    public struct ThirdPersonCharacter_ActionMapActions
    {
        private @PlayerInputActions m_Wrapper;
        public ThirdPersonCharacter_ActionMapActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_ThirdPersonCharacter_ActionMap_Move;
        public InputAction @Jump => m_Wrapper.m_ThirdPersonCharacter_ActionMap_Jump;
        public InputAction @Run => m_Wrapper.m_ThirdPersonCharacter_ActionMap_Run;
        public InputAction @Crouch => m_Wrapper.m_ThirdPersonCharacter_ActionMap_Crouch;
        public InputAction @Shoot => m_Wrapper.m_ThirdPersonCharacter_ActionMap_Shoot;
        public InputAction @ChangeWeapon => m_Wrapper.m_ThirdPersonCharacter_ActionMap_ChangeWeapon;
        public InputAction @SelectWeapon0 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon0;
        public InputAction @SelectWeapon1 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon1;
        public InputAction @SelectWeapon2 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon2;
        public InputAction @SelectWeapon3 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon3;
        public InputAction @SelectWeapon4 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon4;
        public InputAction @SelectWeapon5 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon5;
        public InputAction @SelectWeapon6 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon6;
        public InputAction @SelectWeapon7 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon7;
        public InputAction @SelectWeapon8 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon8;
        public InputAction @SelectWeapon9 => m_Wrapper.m_ThirdPersonCharacter_ActionMap_SelectWeapon9;
        public InputAction @Locking => m_Wrapper.m_ThirdPersonCharacter_ActionMap_Locking;
        public InputActionMap Get() { return m_Wrapper.m_ThirdPersonCharacter_ActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ThirdPersonCharacter_ActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IThirdPersonCharacter_ActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_ThirdPersonCharacter_ActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ThirdPersonCharacter_ActionMapActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @ChangeWeapon.started += instance.OnChangeWeapon;
            @ChangeWeapon.performed += instance.OnChangeWeapon;
            @ChangeWeapon.canceled += instance.OnChangeWeapon;
            @SelectWeapon0.started += instance.OnSelectWeapon0;
            @SelectWeapon0.performed += instance.OnSelectWeapon0;
            @SelectWeapon0.canceled += instance.OnSelectWeapon0;
            @SelectWeapon1.started += instance.OnSelectWeapon1;
            @SelectWeapon1.performed += instance.OnSelectWeapon1;
            @SelectWeapon1.canceled += instance.OnSelectWeapon1;
            @SelectWeapon2.started += instance.OnSelectWeapon2;
            @SelectWeapon2.performed += instance.OnSelectWeapon2;
            @SelectWeapon2.canceled += instance.OnSelectWeapon2;
            @SelectWeapon3.started += instance.OnSelectWeapon3;
            @SelectWeapon3.performed += instance.OnSelectWeapon3;
            @SelectWeapon3.canceled += instance.OnSelectWeapon3;
            @SelectWeapon4.started += instance.OnSelectWeapon4;
            @SelectWeapon4.performed += instance.OnSelectWeapon4;
            @SelectWeapon4.canceled += instance.OnSelectWeapon4;
            @SelectWeapon5.started += instance.OnSelectWeapon5;
            @SelectWeapon5.performed += instance.OnSelectWeapon5;
            @SelectWeapon5.canceled += instance.OnSelectWeapon5;
            @SelectWeapon6.started += instance.OnSelectWeapon6;
            @SelectWeapon6.performed += instance.OnSelectWeapon6;
            @SelectWeapon6.canceled += instance.OnSelectWeapon6;
            @SelectWeapon7.started += instance.OnSelectWeapon7;
            @SelectWeapon7.performed += instance.OnSelectWeapon7;
            @SelectWeapon7.canceled += instance.OnSelectWeapon7;
            @SelectWeapon8.started += instance.OnSelectWeapon8;
            @SelectWeapon8.performed += instance.OnSelectWeapon8;
            @SelectWeapon8.canceled += instance.OnSelectWeapon8;
            @SelectWeapon9.started += instance.OnSelectWeapon9;
            @SelectWeapon9.performed += instance.OnSelectWeapon9;
            @SelectWeapon9.canceled += instance.OnSelectWeapon9;
            @Locking.started += instance.OnLocking;
            @Locking.performed += instance.OnLocking;
            @Locking.canceled += instance.OnLocking;
        }

        private void UnregisterCallbacks(IThirdPersonCharacter_ActionMapActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @ChangeWeapon.started -= instance.OnChangeWeapon;
            @ChangeWeapon.performed -= instance.OnChangeWeapon;
            @ChangeWeapon.canceled -= instance.OnChangeWeapon;
            @SelectWeapon0.started -= instance.OnSelectWeapon0;
            @SelectWeapon0.performed -= instance.OnSelectWeapon0;
            @SelectWeapon0.canceled -= instance.OnSelectWeapon0;
            @SelectWeapon1.started -= instance.OnSelectWeapon1;
            @SelectWeapon1.performed -= instance.OnSelectWeapon1;
            @SelectWeapon1.canceled -= instance.OnSelectWeapon1;
            @SelectWeapon2.started -= instance.OnSelectWeapon2;
            @SelectWeapon2.performed -= instance.OnSelectWeapon2;
            @SelectWeapon2.canceled -= instance.OnSelectWeapon2;
            @SelectWeapon3.started -= instance.OnSelectWeapon3;
            @SelectWeapon3.performed -= instance.OnSelectWeapon3;
            @SelectWeapon3.canceled -= instance.OnSelectWeapon3;
            @SelectWeapon4.started -= instance.OnSelectWeapon4;
            @SelectWeapon4.performed -= instance.OnSelectWeapon4;
            @SelectWeapon4.canceled -= instance.OnSelectWeapon4;
            @SelectWeapon5.started -= instance.OnSelectWeapon5;
            @SelectWeapon5.performed -= instance.OnSelectWeapon5;
            @SelectWeapon5.canceled -= instance.OnSelectWeapon5;
            @SelectWeapon6.started -= instance.OnSelectWeapon6;
            @SelectWeapon6.performed -= instance.OnSelectWeapon6;
            @SelectWeapon6.canceled -= instance.OnSelectWeapon6;
            @SelectWeapon7.started -= instance.OnSelectWeapon7;
            @SelectWeapon7.performed -= instance.OnSelectWeapon7;
            @SelectWeapon7.canceled -= instance.OnSelectWeapon7;
            @SelectWeapon8.started -= instance.OnSelectWeapon8;
            @SelectWeapon8.performed -= instance.OnSelectWeapon8;
            @SelectWeapon8.canceled -= instance.OnSelectWeapon8;
            @SelectWeapon9.started -= instance.OnSelectWeapon9;
            @SelectWeapon9.performed -= instance.OnSelectWeapon9;
            @SelectWeapon9.canceled -= instance.OnSelectWeapon9;
            @Locking.started -= instance.OnLocking;
            @Locking.performed -= instance.OnLocking;
            @Locking.canceled -= instance.OnLocking;
        }

        public void RemoveCallbacks(IThirdPersonCharacter_ActionMapActions instance)
        {
            if (m_Wrapper.m_ThirdPersonCharacter_ActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IThirdPersonCharacter_ActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_ThirdPersonCharacter_ActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ThirdPersonCharacter_ActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ThirdPersonCharacter_ActionMapActions @ThirdPersonCharacter_ActionMap => new ThirdPersonCharacter_ActionMapActions(this);
    public interface IThirdPersonCharacter_ActionMapActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnChangeWeapon(InputAction.CallbackContext context);
        void OnSelectWeapon0(InputAction.CallbackContext context);
        void OnSelectWeapon1(InputAction.CallbackContext context);
        void OnSelectWeapon2(InputAction.CallbackContext context);
        void OnSelectWeapon3(InputAction.CallbackContext context);
        void OnSelectWeapon4(InputAction.CallbackContext context);
        void OnSelectWeapon5(InputAction.CallbackContext context);
        void OnSelectWeapon6(InputAction.CallbackContext context);
        void OnSelectWeapon7(InputAction.CallbackContext context);
        void OnSelectWeapon8(InputAction.CallbackContext context);
        void OnSelectWeapon9(InputAction.CallbackContext context);
        void OnLocking(InputAction.CallbackContext context);
    }
}
